# Introduction to Scikit-Learn(skearn)

0. An end-to-end Scikit-Learn workflow
1. Getting data ready
2. Choose right estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Put it all together!

In [8]:
# standard imports
import numpy as np

## 0. End-to-end Scikit-Learn workflow

In [1]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("data/heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [2]:
# Create X(features matrix)
x = heart_disease.drop("target", axis=1)

# Create y(labels)
y = heart_disease["target"]

In [3]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# Keeping the default hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3. Fit the model to the data
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [7]:
clf.fit(x_train,y_train);

In [10]:
# Make a prediction
y_label = clf.predict(np.array([[57,0,0,120,354,0,1,163,1,0.6,2,0,2]]))
y_label

C:\Users\Ashu\Desktop\Intro_ML_LIb\env\lib\site-packages\sklearn\base.py:445: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [11]:
y_preds = clf.predict(x_test)
y_preds

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0], dtype=int64)

In [12]:
y_test

190    0
215    0
130    1
44     1
184    0
      ..
10     1
247    0
2      1
52     1
166    0
Name: target, Length: 61, dtype: int64

In [13]:
# 4. Evaluate the model
clf.score(x_train,y_train)

1.0

In [14]:
clf.score(x_test,y_test)

0.9016393442622951

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.87      0.87      0.87        23
           1       0.92      0.92      0.92        38

    accuracy                           0.90        61
   macro avg       0.90      0.90      0.90        61
weighted avg       0.90      0.90      0.90        61



In [16]:
confusion_matrix(y_test,y_preds)

array([[20,  3],
       [ 3, 35]], dtype=int64)

In [17]:
accuracy_score(y_test,y_preds)

0.9016393442622951

In [19]:
# 5. Improve a model
#  Try different amount of n_estimators
np.random.seed(42)
for i in range(10,100,10):
    print(f"Trying model with {i} estimators...")
    clf=RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"Model accuracy ont test set: {clf.score(x_test,y_test)}")
    print("")

Trying model with 10 estimators...
Model accuracy ont test set: 0.7540983606557377

Trying model with 20 estimators...
Model accuracy ont test set: 0.8852459016393442

Trying model with 30 estimators...
Model accuracy ont test set: 0.8524590163934426

Trying model with 40 estimators...
Model accuracy ont test set: 0.8524590163934426

Trying model with 50 estimators...
Model accuracy ont test set: 0.8688524590163934

Trying model with 60 estimators...
Model accuracy ont test set: 0.8524590163934426

Trying model with 70 estimators...
Model accuracy ont test set: 0.8360655737704918

Trying model with 80 estimators...
Model accuracy ont test set: 0.8524590163934426

Trying model with 90 estimators...
Model accuracy ont test set: 0.9016393442622951



In [20]:
# 6. Save a model and load it
import pickle

pickle.dump(clf,open("random_forst_model1.pkl","wb"))

In [21]:
loaded_model = pickle.load(open("random_forst_model1.pkl","rb"))
loaded_model.score(x_test,y_test)

0.9016393442622951