In [5]:
import numpy as np

# DataTypes and Attributes

In [6]:
# Numpy's main datatype is ndarray

In [7]:
a1=np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [8]:
type(a1)

numpy.ndarray

In [9]:
a2=np.array([[1,2,3.7],
            [2.4,3,4]])
a3=np.array([[[1,2,3],
             [1.2,3,5]],
            
            [[1,22,3.6],
            [2,3,4]]])

In [10]:
a2

array([[1. , 2. , 3.7],
       [2.4, 3. , 4. ]])

In [11]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 1.2,  3. ,  5. ]],

       [[ 1. , 22. ,  3.6],
        [ 2. ,  3. ,  4. ]]])

In [12]:
a1.shape

(4,)

In [13]:
a2.shape


(2, 3)

In [14]:
a3.shape

(2, 2, 3)

In [15]:
a3.ndim

3

In [16]:
a1.dtype

dtype('int32')

In [17]:
a1.size

4

In [18]:
a3.size

12

In [19]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
#Create a DataFrame from NumPy array
import pandas as pd

df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.7
1  2.4  3.0  4.0

# Creating Arrays

In [21]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
zeros=np.zeros((3,3),int)
zeros

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
range_array = np.arange(0,10,2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size=(3,4))
random_array

array([[3, 7, 1, 4],
       [5, 5, 1, 9],
       [0, 3, 3, 6]])

In [27]:
random_array2=np.random.random((5,3))
random_array2

array([[0.16559171, 0.12037229, 0.88790778],
       [0.8243882 , 0.54495144, 0.79031683],
       [0.20434826, 0.58839258, 0.65200724],
       [0.76735201, 0.49690457, 0.85356907],
       [0.29411394, 0.94742906, 0.45849198]])

In [28]:
#pseudo-random numbers
np.random.seed(4)
random_array4=np.random.randint(10,size=(5,3))
random_array4

array([[7, 5, 1],
       [8, 7, 8],
       [2, 9, 7],
       [7, 7, 9],
       [8, 4, 2]])

# Viewing arrays and metrices

In [29]:
np.unique(random_array2)

array([0.12037229, 0.16559171, 0.20434826, 0.29411394, 0.45849198,
       0.49690457, 0.54495144, 0.58839258, 0.65200724, 0.76735201,
       0.79031683, 0.8243882 , 0.85356907, 0.88790778, 0.94742906])

In [30]:
np.unique(random_array)

array([0, 1, 3, 4, 5, 6, 7, 9])

In [31]:
a3[0]

array([[1. , 2. , 3. ],
       [1.2, 3. , 5. ]])

In [32]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 1.2,  3. ,  5. ]],

       [[ 1. , 22. ,  3.6],
        [ 2. ,  3. ,  4. ]]])

In [33]:
a3[0][1]

array([1.2, 3. , 5. ])

In [34]:
a3[0][1][1]

3.0

In [35]:
a3[:2,:2,:2]

array([[[ 1. ,  2. ],
        [ 1.2,  3. ]],

       [[ 1. , 22. ],
        [ 2. ,  3. ]]])

In [36]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 4, 3, 0, 7],
         [5, 5, 9, 6, 6],
         [8, 2, 5, 8, 1],
         [2, 7, 0, 8, 3]],

        [[1, 0, 3, 2, 3],
         [2, 9, 2, 1, 0],
         [1, 9, 9, 0, 7],
         [2, 6, 3, 7, 8]],

        [[2, 6, 7, 7, 9],
         [2, 7, 5, 3, 0],
         [5, 4, 3, 8, 9],
         [5, 8, 6, 7, 0]]],


       [[[4, 6, 8, 4, 8],
         [1, 9, 5, 4, 2],
         [3, 4, 7, 6, 6],
         [8, 0, 3, 5, 6]],

        [[1, 1, 6, 0, 8],
         [7, 5, 7, 6, 8],
         [4, 4, 0, 7, 2],
         [1, 8, 8, 1, 3]],

        [[1, 3, 6, 7, 4],
         [0, 7, 3, 7, 9],
         [6, 6, 9, 3, 2],
         [7, 6, 7, 9, 4]]]])

In [37]:
a4[:,:,:,:2]

array([[[[6, 4],
         [5, 5],
         [8, 2],
         [2, 7]],

        [[1, 0],
         [2, 9],
         [1, 9],
         [2, 6]],

        [[2, 6],
         [2, 7],
         [5, 4],
         [5, 8]]],


       [[[4, 6],
         [1, 9],
         [3, 4],
         [8, 0]],

        [[1, 1],
         [7, 5],
         [4, 4],
         [1, 8]],

        [[1, 3],
         [0, 7],
         [6, 6],
         [7, 6]]]])

# Manipulating & comparing arrays

## Airthmetic

In [38]:
a1

array([1, 2, 3, 4])

In [39]:
ones =np.ones(4)
ones

array([1., 1., 1., 1.])

In [40]:
a1+ones

array([2., 3., 4., 5.])

In [41]:
a1-ones

array([0., 1., 2., 3.])

In [42]:
a1 * ones

array([1., 2., 3., 4.])

In [45]:
a2

array([[1. , 2. , 3.7],
       [2.4, 3. , 4. ]])

In [47]:
a2* a3

array([[[ 1.  ,  4.  , 11.1 ],
        [ 2.88,  9.  , 20.  ]],

       [[ 1.  , 44.  , 13.32],
        [ 4.8 ,  9.  , 16.  ]]])

In [48]:
a1 ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [49]:
np.square(a1)

array([ 1,  4,  9, 16], dtype=int32)